import React from 'react';
import { ArrowLeft, Shield, Scale, FileText, AlertTriangle } from 'lucide-react';

interface TermsProps {
  onBack: () => void;
}

const Terms: React.FC<TermsProps> = ({ onBack }) => {
  return (
    <div className="w-full max-w-4xl mt-8 mb-12 animate-in fade-in slide-in-from-bottom-4 duration-500">
      <div className="flex items-center mb-6">
        <button 
          onClick={onBack}
          className="flex items-center gap-2 text-pink-400 hover:text-pink-300 transition-colors group"
        >
          <ArrowLeft className="w-5 h-5 group-hover:-translate-x-1 transition-transform" />
          <span className="font-heading uppercase tracking-widest text-sm">Back to Countdown</span>
        </button>
      </div>

      <div className="bg-black/40 backdrop-blur-md border border-white/10 rounded-2xl p-6 md:p-10 shadow-2xl">
        <div className="flex items-center gap-3 mb-8 border-b border-white/5 pb-6">
          <Scale className="w-8 h-8 text-pink-500" />
          <h2 className="text-3xl md:text-4xl font-heading font-bold text-white">Terms & Legal</h2>
        </div>

        <div className="space-y-8 text-gray-300 font-light leading-relaxed">
          
          <section className="space-y-3">
            <h3 className="flex items-center gap-2 text-xl font-bold text-teal-400">
              <Shield className="w-5 h-5" />
              1. Fan Site Disclaimer
            </h3>
            <p>
              This website ("Project Americas Countdown") is a strictly non-commercial fan project. We are not affiliated with, associated with, authorized by, endorsed by, or in any way officially connected with <strong className="text-white">Rockstar Games</strong>, <strong className="text-white">Take-Two Interactive</strong>, or any of their subsidiaries or affiliates.
            </p>
            <p>
              The names "Grand Theft Auto", "GTA VI", "Vice City", and related marks, emblems, and images are registered trademarks of their respective owners.
            </p>
          </section>

          <section className="space-y-3">
            <h3 className="flex items-center gap-2 text-xl font-bold text-teal-400">
              <FileText className="w-5 h-5" />
              2. Content & Assets
            </h3>
            <p>
              This site is intended for educational and entertainment purposes only under the "Fair Use" doctrine. 
            </p>
            <ul className="list-disc list-inside space-y-2 ml-4 text-gray-400">
              <li>Visual assets are either original, simulated CSS/SVG graphics, or used for transformative commentary.</li>
              <li>News headlines are generated by Artificial Intelligence (Google Gemini) for satirical purposes and do not represent real-world events or official game lore.</li>
              <li>Countdown dates are speculative estimates based on public industry analysis and are subject to change by the official rights holders.</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h3 className="flex items-center gap-2 text-xl font-bold text-teal-400">
              <AlertTriangle className="w-5 h-5" />
              3. Open Source & Licensing
            </h3>
            <p>
              The source code for this specific web presentation is provided "as is", without warranty of any kind, express or implied.
            </p>
            <p className="text-sm border-l-2 border-pink-500/50 pl-4 py-1 bg-white/5">
              "THE SOFTWARE IS PROVIDED 'AS IS', WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT."
            </p>
          </section>

        </div>

        <div className="mt-10 pt-6 border-t border-white/5 text-center">
            <p className="text-xs text-gray-500">
                Last Updated: {new Date().toLocaleDateString()}
            </p>
        </div>
      </div>
    </div>
  );
};

export default Terms;